on: [push, pull_request]

name: Rust CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Format check
        run: cargo fmt --check
      - name: Cargo check
        run: cargo check
      - name: Cargo test
        run: cargo test
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g cspell
      - name: Typos
        run: cspell "*.md" "src/**"
